# **Principal Component Analysis**

**Formally, PCA is a statistical technique for reducing the dimensionality of a dataset. This is accomplished by linearly transforming the data into a new coordinate system where (most of) the variation in the data can be described with fewer dimensions than the initial data.**

In [1]:
import numpy as np
import pandas as pd 
import plotly
import plotly.express as px
plotly.offline.init_notebook_mode (connected = True)

In [2]:
df = px.data.iris() # Iris dataset

In [3]:
df = df.drop(['petal_length', 'species_id'], axis=1) # Only 3 features are considered

In [4]:
df.head()

sepal_length  sepal_width  petal_width species
0           5.1          3.5          0.2  setosa
1           4.9          3.0          0.2  setosa
2           4.7          3.2          0.2  setosa
3           4.6          3.1          0.2  setosa
4           5.0          3.6          0.2  setosa

In [5]:
df.corr().style.background_gradient(cmap='coolwarm') # Correlation between features as a heatmap

/tmp/ipykernel_19391/268667714.py:1: FutureWarning:

The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.



In [28]:
feats = df.columns[:-1]
print(feats)

Index(['sepal_length', 'sepal_width', 'petal_width'], dtype='object')


## Checking the range of each feature

In [7]:
fig = px.bar(df[feats].min(), title='Features Min Values')
fig.layout.xaxis.tickangle = 300
fig.update_traces(showlegend = False)
fig.layout.xaxis. dtick = 5
fig.layout.xaxis.title = ''
fig.layout.yaxis.title = ''
fig.show()

In [8]:
fig = px.bar(df[feats].max(), title='Features Max Values')
fig.layout.xaxis.tickangle = 300
fig.update_traces(showlegend = False)
fig.layout.xaxis. dtick = 5
fig.layout.xaxis.title = ''
fig.layout.yaxis.title = ''
fig.show()

## Scaling the features using standardization

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit_transform(df[feats])

In [10]:
scaled = pd.DataFrame(scaler, columns=feats)
scaled['species'] = df['species']
scaled

sepal_length  sepal_width  petal_width    species
0       -0.900681     1.032057    -1.312977     setosa
1       -1.143017    -0.124958    -1.312977     setosa
2       -1.385353     0.337848    -1.312977     setosa
3       -1.506521     0.106445    -1.312977     setosa
4       -1.021849     1.263460    -1.312977     setosa
..            ...          ...          ...        ...
145      1.038005    -0.124958     1.447956  virginica
146      0.553333    -1.281972     0.922064  virginica
147      0.795669    -0.124958     1.053537  virginica
148      0.432165     0.800654     1.447956  virginica
149      0.068662    -0.124958     0.790591  virginica

[150 rows x 4 columns]

## After scaling

In [11]:
fig = px.bar(scaled[feats].min(), title='Features Min Values')
fig.layout.xaxis.tickangle = 300
fig.update_traces(showlegend = False)
fig.layout.xaxis. dtick = 5
fig.layout.xaxis.title = ''
fig.layout.yaxis.title = ''
fig.show()

In [12]:
fig = px.bar(scaled[feats].max(), title='Features Max Values')
fig.layout.xaxis.tickangle = 300
fig.update_traces(showlegend = False)
fig.layout.xaxis. dtick = 5
fig.layout.xaxis.title = ''
fig.layout.yaxis.title = ''
fig.show()

# Before PCA

In [13]:
fig = px.scatter_3d(scaled, x='sepal_length', y='sepal_width', z='petal_width',
              color='species', symbol='species')
fig.update_layout(width=800, height=800)
fig.update_traces(marker=dict(size=2.5))
fig.show()

In [14]:
df.head()

sepal_length  sepal_width  petal_width species
0           5.1          3.5          0.2  setosa
1           4.9          3.0          0.2  setosa
2           4.7          3.2          0.2  setosa
3           4.6          3.1          0.2  setosa
4           5.0          3.6          0.2  setosa

In [15]:
X, y = df.drop(['species'], axis=1), df['species']

In [16]:
from sklearn.decomposition import PCA

In [17]:
# Function to create pca with 'n' components
def create_pca(X, y, n_components=None):
    if (n_components != None):
        pca = PCA(n_components)
    else:
        pca = PCA()
    trans = pca.fit_transform(X)
    trans = pd.DataFrame(trans)
    trans['species'] = y
    return pca, trans

# After PCA

In [18]:
pca1, trans1 = create_pca(X=X, y=y, n_components=3)
pca2, trans2 = create_pca(X=X, y=y, n_components=2)
pca3, trans3 = create_pca(X=X, y=y, n_components=1)

## n components = 3

In [19]:
pca1.explained_variance_ratio_

array([0.8004668 , 0.14652357, 0.05300962])

In [20]:
# Eigenvectors for the 3 variables
pca1.components_

array([[ 0.73255285, -0.11049104,  0.671683  ],
       [ 0.42368818,  0.84631288, -0.32286659],
       [-0.53278011,  0.52110099,  0.66678266]])

In [21]:
fig = px.scatter_3d(trans1, x=0, y=1, z=2, color='species', symbol='species')
fig.update_layout(width=800, height=800)
fig.update_traces(marker=dict(size=2.5))
fig.show()

## n components = 2

In [22]:
pca2.explained_variance_ratio_

array([0.8004668 , 0.14652357])

In [23]:
# Eigenvectors for the s variables
pca2.components_

array([[ 0.73255285, -0.11049104,  0.671683  ],
       [ 0.42368818,  0.84631288, -0.32286659]])

In [24]:
fig = px.scatter(trans2, x=0, y=1, color='species', symbol='species')
fig.update_traces(marker=dict(size=5))
fig.show()

## n components = 1

In [25]:
pca3.explained_variance_ratio_

array([0.8004668])

In [26]:
# Eigenvectors for the 1 variable
pca3.components_

array([[ 0.73255285, -0.11049104,  0.671683  ]])

In [27]:
trans3[1] = np.zeros_like(trans3[0]) + 1
fig = px.scatter(trans3, x=0, y=1, color='species', symbol='species')
fig.update_traces(marker=dict(size=5))
fig.show()